module.exports = [
  { hex: "#000000", en: "Black", it: "Nero" },
  { hex: "#000080", en: "Navy blue", it: "Blu marino" },
  { hex: "#00008b", en: "Dark blue", it: "Blu scuro" },
  { hex: "#0000ff", en: "Blue", it: "Blu" },
  { hex: "#006400", en: "Dark green", it: "Verde scuro" },
  { hex: "#008000", en: "Green", it: "Verde" },
  { hex: "#008080", en: "Teal", it: "Verde acqua" },
  { hex: "#00ff00", en: "Lime", it: "Lime" },
  { hex: "#00ffff", en: "Cyan", it: "Ciano" },
  { hex: "#191970", en: "Midnight blue", it: "Blu notte" },
  { hex: "#2E8B57", en: "Sea green", it: "Verde mare" },
  { hex: "#40e0d0", en: "Turquoise", it: "Turchese" },
  { hex: "#4b0082", en: "Indigo", it: "Indaco" },
  { hex: "#7fffd4", en: "Aquamarine", it: "Acquamarina" },
  { hex: "#800000", en: "Maroon", it: "Bordeaux" },
  { hex: "#800080", en: "Purple", it: "Viola" },
  { hex: "#808000", en: "Olive", it: "Oliva" },
  { hex: "#808080", en: "Gray", it: "Grigio" },
  { hex: "#87ceeb", en: "Sky blue", it: "Blu cielo" },
  { hex: "#8b0000", en: "Dark red", it: "Rosso scuro" },
  { hex: "#90ee90", en: "Light green", it: "Verde chiaro" },
  { hex: "#a52a2a", en: "Brown", it: "Marrone" },
  { hex: "#a9a9a9", en: "Dark gray", it: "Grigio scuro" },
  { hex: "#add8e6", en: "Light blue", it: "Azzurro" },
  { hex: "#c0c0c0", en: "Silver", it: "Argento" },
  { hex: "#d2b48c", en: "Tan", it: "Beige" },
  { hex: "#d3d3d3", en: "Light gray", it: "Grigio chiaro" },
  { hex: "#dc143c", en: "Crimson", it: "Cremisi" },
  { hex: "#dda0dd", en: "Plum", it: "Prugna" },
  { hex: "#e6e6fa", en: "Lavender", it: "Lavanda" },
  { hex: "#f0e68c", en: "Khaki", it: "Kaki" },
  { hex: "#fa8072", en: "Salmon", it: "Salmone" },
  { hex: "#ff0000", en: "Red", it: "Rosso" },
  { hex: "#ff00ff", en: "Fuchsia", it: "Fucsia" },
  { hex: "#ff7f50", en: "Coral", it: "Corallo" },
  { hex: "#ffa500", en: "Orange", it: "Arancione" },
  { hex: "#ffc0cb", en: "Pink", it: "Rosa" },
  { hex: "#ffd700", en: "Gold", it: "Oro" },
  { hex: "#fffafa", en: "Snow", it: "Neve" },
  { hex: "#ffff00", en: "Yellow", it: "Giallo" },
  { hex: "#ffffff", en: "White", it: "Bianco" },
];
